server:
  port: 8001
spring:
  application:
    name: booking
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/otabooking
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




#application:
#  config:
#    students-url: http://localhost:8222/api/v1/students

logging:
  level:
    org.hibernate.SQL: DEBUG  # Log SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Log bound parameters
    org.springframework.data.jpa.repository.query: DEBUG  # Log JPA repository queries
