spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration/
  profiles:
    active: native

server:
  port: 8888
