spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration/
  profiles:
    active: native

server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
